// =====================================================================
// fe_big_emoji_pixel_rom.sv  --  4 bpp tile bitmap ROM for big emojis
// ---------------------------------------------------------------------
// 96 tile slots (corresponding to codes 0x80..0xDF) x 16 rows of 8 nibbles.
// Address = {tile_off[6:0], gy[3:0]} (11 bits). Each addressed entry is
// a 32-bit row holding 8 palette indices, MSB-first (gx=0 in bits[31:28]).
//
// Initialised from FONT_PIXEL_HEX (default rtl/frontend/fe_big_emoji_pixels.hex)
// via $readmemh, generated by scripts/gen_big_emoji.py.
//
// Read latency: combinational, matches fe_glyph_rom convention.
// =====================================================================

`ifndef FE_BIG_EMOJI_PIXEL_ROM_SV
`define FE_BIG_EMOJI_PIXEL_ROM_SV

module fe_big_emoji_pixel_rom (
    input  logic [6:0]  tile_off,   // code - 0x80
    input  logic [3:0]  gy,
    output logic [31:0] row
);

    logic [31:0] mem [2048];

    // Hex file lookup mirrors fe_glyph_rom.sv: Vivado synth searches the
    // source-file directory, Verilator runs with cwd=repo-root.
    initial begin
`ifdef SYNTHESIS
        $readmemh("fe_big_emoji_pixels.hex", mem);
`else
        $readmemh("rtl/frontend/fe_big_emoji_pixels.hex", mem);
`endif
    end

    assign row = mem[{tile_off, gy}];

endmodule

`endif  // FE_BIG_EMOJI_PIXEL_ROM_SV
