// =====================================================================
// fe_glyph_rom.sv  --  8x16 character bitmap ROM
// ---------------------------------------------------------------------
// 256 code points x 16 rows x 8 columns of bitmap. Address = {code,
// gy} (12 bits). Bit 7 of the returned byte is the leftmost pixel.
//
// Initialised from FONT_HEX (default rtl/frontend/fe_font.hex), which
// is generated by scripts/gen_font.py. Replace that script (or its
// output) to swap in a different font without touching this module.
//
// Sprite codes 0xF0..0xFF are reserved for status icons / small
// emojis; the same address space and lookup applies.
//
// Read latency: combinational (one BRAM-cycle equivalent). The scan
// pipeline expects glyph_row to update in the same cycle that text_ram
// produces a new code.
// =====================================================================

`ifndef FE_GLYPH_ROM_SV
`define FE_GLYPH_ROM_SV

module fe_glyph_rom (
    input  logic [7:0] code,
    input  logic [3:0] gy,
    output logic [7:0] glyph_row
);

    logic [7:0] mem [4096];

    // The font path differs between toolchains:
    //   - Vivado synth runs from chat.runs/synth_1/ but searches the
    //     source file's directory first; fe_font.hex sits beside this
    //     .sv (in rtl/frontend/, exposed via the chat.srcs/sources_1/
    //     new symlink) so the bare filename is enough.
    //   - Verilator tests run with cwd=repo-root, so the path is
    //     rtl/frontend/fe_font.hex.
    initial begin
`ifdef SYNTHESIS
        $readmemh("fe_font.hex", mem);
`else
        $readmemh("rtl/frontend/fe_font.hex", mem);
`endif
    end

    assign glyph_row = mem[{code, gy}];

endmodule

`endif  // FE_GLYPH_ROM_SV
