// =====================================================================
// fe_glyph_rom.sv  --  8x16 character bitmap ROM
// ---------------------------------------------------------------------
// 256 code points x 16 rows x 8 columns of bitmap. Address = {code,
// gy} (12 bits). Bit 7 of the returned byte is the leftmost pixel.
//
// Initialised from FONT_HEX (default rtl/frontend/fe_font.hex), which
// is generated by scripts/gen_font.py. Replace that script (or its
// output) to swap in a different font without touching this module.
//
// Sprite codes 0xF0..0xFF are reserved for status icons / small
// emojis; the same address space and lookup applies.
//
// Read latency: combinational (one BRAM-cycle equivalent). The scan
// pipeline expects glyph_row to update in the same cycle that text_ram
// produces a new code.
// =====================================================================

`ifndef FE_GLYPH_ROM_SV
`define FE_GLYPH_ROM_SV

module fe_glyph_rom
    import fe_pkg::*;
(
    input  logic [7:0] code,
    input  logic [3:0] gy,
    output logic [7:0] glyph_row
);

    logic [7:0] mem [4096];

    initial begin
        $readmemh(FONT_HEX, mem);
    end

    assign glyph_row = mem[{code, gy}];

endmodule

`endif  // FE_GLYPH_ROM_SV
