// AUTO-GENERATED by scripts/gen_big_emoji.py -- do not edit by hand.
// Anchor codes + sizing constants for big-emoji bubbles. Tile codes
// for one emoji occupy [anchor, anchor + N_TILES - 1]; both the pixel
// ROM and palette derive offsets from these constants.

localparam int BIG_EMOJI_BASE     = 'h80;
localparam int BIG_EMOJI_N_ROWS   = 3;
localparam int BIG_EMOJI_N_COLS   = 6;
localparam int BIG_EMOJI_N_TILES  = 18;
localparam int BIG_EMOJI_COUNT    = 5;
localparam int BIG_EMOJI_END_EXCL = 'hDA;

localparam byte_t BIG_EMOJI_HEARTBROKEN_ANCHOR = 8'h80;  // tiles 0x80..0x91
localparam byte_t BIG_EMOJI_HISSING_ANCHOR = 8'h92;  // tiles 0x92..0xA3
localparam byte_t BIG_EMOJI_SHRUG_ANCHOR = 8'hA4;  // tiles 0xA4..0xB5
localparam byte_t BIG_EMOJI_SWEAT_ANCHOR = 8'hB6;  // tiles 0xB6..0xC7
localparam byte_t BIG_EMOJI_XIUCAI_ANCHOR = 8'hC8;  // tiles 0xC8..0xD9
