// AUTO-GENERATED by scripts/gen_big_emoji.py -- do not edit by hand.
// Big-emoji backslash tokens. Each branch matches "\Name"
// (capital first letter) and emits the single anchor byte; the
// frontend expands the anchor into a 3x6 tile bubble on render.

else if ((src + 11 < int'(len_q))
      && (line_buf[src + 0] == 8'h5C)
      && (line_buf[src + 1] == "H")
      && (line_buf[src + 2] == "e")
      && (line_buf[src + 3] == "a")
      && (line_buf[src + 4] == "r")
      && (line_buf[src + 5] == "t")
      && (line_buf[src + 6] == "b")
      && (line_buf[src + 7] == "r")
      && (line_buf[src + 8] == "o")
      && (line_buf[src + 9] == "k")
      && (line_buf[src + 10] == "e")
      && (line_buf[src + 11] == "n")) begin
    encoded_line_payload[dst*8 +: 8] = 8'h80;  // \Heartbroken
    src += 12;
    dst += 1;
end
else if ((src + 7 < int'(len_q))
      && (line_buf[src + 0] == 8'h5C)
      && (line_buf[src + 1] == "H")
      && (line_buf[src + 2] == "i")
      && (line_buf[src + 3] == "s")
      && (line_buf[src + 4] == "s")
      && (line_buf[src + 5] == "i")
      && (line_buf[src + 6] == "n")
      && (line_buf[src + 7] == "g")) begin
    encoded_line_payload[dst*8 +: 8] = 8'h92;  // \Hissing
    src += 8;
    dst += 1;
end
else if ((src + 5 < int'(len_q))
      && (line_buf[src + 0] == 8'h5C)
      && (line_buf[src + 1] == "S")
      && (line_buf[src + 2] == "h")
      && (line_buf[src + 3] == "r")
      && (line_buf[src + 4] == "u")
      && (line_buf[src + 5] == "g")) begin
    encoded_line_payload[dst*8 +: 8] = 8'hA4;  // \Shrug
    src += 6;
    dst += 1;
end
else if ((src + 5 < int'(len_q))
      && (line_buf[src + 0] == 8'h5C)
      && (line_buf[src + 1] == "S")
      && (line_buf[src + 2] == "w")
      && (line_buf[src + 3] == "e")
      && (line_buf[src + 4] == "a")
      && (line_buf[src + 5] == "t")) begin
    encoded_line_payload[dst*8 +: 8] = 8'hB6;  // \Sweat
    src += 6;
    dst += 1;
end
else if ((src + 6 < int'(len_q))
      && (line_buf[src + 0] == 8'h5C)
      && (line_buf[src + 1] == "X")
      && (line_buf[src + 2] == "i")
      && (line_buf[src + 3] == "u")
      && (line_buf[src + 4] == "c")
      && (line_buf[src + 5] == "a")
      && (line_buf[src + 6] == "i")) begin
    encoded_line_payload[dst*8 +: 8] = 8'hC8;  // \Xiucai
    src += 7;
    dst += 1;
end
