// AUTO-GENERATED by scripts/gen_big_emoji.py -- do not edit by hand.
// Big-emoji backslash tokens. Each branch matches "\Name"
// (capital first letter) only when it is the entire input line,
// then emits the single anchor byte; the frontend expands the
// anchor into a 3x6 tile bubble on render.
// Suppressed while a quote is active (has_quote_q): a big emoji
// cannot carry a quote, so the token stays literal text instead.

else if ((src == 0)
      && !has_quote_q
      && (12 == int'(len_q))
      && (src + 11 < int'(len_q))
      && (line_buf[src + 0] == 8'h5C)
      && (line_buf[src + 1] == "H")
      && (line_buf[src + 2] == "e")
      && (line_buf[src + 3] == "a")
      && (line_buf[src + 4] == "r")
      && (line_buf[src + 5] == "t")
      && (line_buf[src + 6] == "b")
      && (line_buf[src + 7] == "r")
      && (line_buf[src + 8] == "o")
      && (line_buf[src + 9] == "k")
      && (line_buf[src + 10] == "e")
      && (line_buf[src + 11] == "n")) begin
    enc_emit_byte = 8'h80;  // \Heartbroken
    enc_src_delta = 4'd12;
end
else if ((src == 0)
      && !has_quote_q
      && (8 == int'(len_q))
      && (src + 7 < int'(len_q))
      && (line_buf[src + 0] == 8'h5C)
      && (line_buf[src + 1] == "H")
      && (line_buf[src + 2] == "i")
      && (line_buf[src + 3] == "s")
      && (line_buf[src + 4] == "s")
      && (line_buf[src + 5] == "i")
      && (line_buf[src + 6] == "n")
      && (line_buf[src + 7] == "g")) begin
    enc_emit_byte = 8'h92;  // \Hissing
    enc_src_delta = 4'd8;
end
else if ((src == 0)
      && !has_quote_q
      && (6 == int'(len_q))
      && (src + 5 < int'(len_q))
      && (line_buf[src + 0] == 8'h5C)
      && (line_buf[src + 1] == "S")
      && (line_buf[src + 2] == "h")
      && (line_buf[src + 3] == "r")
      && (line_buf[src + 4] == "u")
      && (line_buf[src + 5] == "g")) begin
    enc_emit_byte = 8'hA4;  // \Shrug
    enc_src_delta = 4'd6;
end
else if ((src == 0)
      && !has_quote_q
      && (6 == int'(len_q))
      && (src + 5 < int'(len_q))
      && (line_buf[src + 0] == 8'h5C)
      && (line_buf[src + 1] == "S")
      && (line_buf[src + 2] == "w")
      && (line_buf[src + 3] == "e")
      && (line_buf[src + 4] == "a")
      && (line_buf[src + 5] == "t")) begin
    enc_emit_byte = 8'hB6;  // \Sweat
    enc_src_delta = 4'd6;
end
else if ((src == 0)
      && !has_quote_q
      && (7 == int'(len_q))
      && (src + 6 < int'(len_q))
      && (line_buf[src + 0] == 8'h5C)
      && (line_buf[src + 1] == "X")
      && (line_buf[src + 2] == "i")
      && (line_buf[src + 3] == "u")
      && (line_buf[src + 4] == "c")
      && (line_buf[src + 5] == "a")
      && (line_buf[src + 6] == "i")) begin
    enc_emit_byte = 8'hC8;  // \Xiucai
    enc_src_delta = 4'd7;
end
