// AUTO-GENERATED by scripts/gen_big_emoji.py -- do not edit by hand.
#pragma once

static constexpr int BIG_EMOJI_BASE    = 0x80;
static constexpr int BIG_EMOJI_N_ROWS  = 3;
static constexpr int BIG_EMOJI_N_COLS  = 6;
static constexpr int BIG_EMOJI_N_TILES = 18;
static constexpr int BIG_EMOJI_COUNT   = 5;

static constexpr int BIG_EMOJI_HEARTBROKEN_ANCHOR = 0x80;
static constexpr int BIG_EMOJI_HISSING_ANCHOR = 0x92;
static constexpr int BIG_EMOJI_SHRUG_ANCHOR = 0xA4;
static constexpr int BIG_EMOJI_SWEAT_ANCHOR = 0xB6;
static constexpr int BIG_EMOJI_XIUCAI_ANCHOR = 0xC8;
